# Site settings
title: Jason Wells
email: flipstock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Husband and father living in Utah (the 11th state I've called home).
  I'm a technology geek and enjoy baseball, tennis, the outdoors, and good food.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasonwells.co" # the base hostname & protocol for your site
twitter_username: wellsja
github_username:  jasonwells

# Build settings
markdown: kramdown
